---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        name:
          - clickhouse-common
          - clickhouse-client
          - clickhouse-server
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  become: true
  hosts: clickhouse
  handlers:
  - name: Restart vector
    ansible.builtin.service:
      name: vector
      state: restarted
  tasks:
    - name: Install Vector
      ansible.builtin.apt:
        deb: "https://packages.timber.io/vector/0.33.0/vector_0.33.0-1_amd64.deb"
        state: present
    - name: copy config
      ansible.builtin.template:
        src: "{{ vector_template }}"
        dest: "{{ vector_config_file }}"
        mode: 0644
      notify: Restart vector
    - name: use the right config
      lineinfile:
        path: /etc/default/vector
        line: "VECTOR_CONFIG={{ vector_config_file }}"
        state: present
      notify: Restart vector
    - name: add vector user to systemd-journal group
      user:
        name: vector
        groups: systemd-journal
        append: true
    - name: start vector
      service:
        name: vector
        state: started
        enabled: true

- name: Install nginx and get lighthouse
  become: true
  hosts: clickhouse
  handlers:
    - name: restart Nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: install nginx
      apt:
        name: nginx
    - name: get lighthouse from git
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse"
        dest: "{{ lighthouse_path }}"
    - name: copy nginx config
      template:
        src: "./templates/lighthouse.j2"
        dest: "/etc/nginx/sites-enabled/lighthouse"
        mode: 0644
      notify: restart Nginx